server:
  port: 9000
spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8091/realms/het-security-realm
management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - circuitbreakers

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 8
        failureRateThreshold: 20
        minimum-number-of-calls: 4
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      userServiceCircuitBreaker:
        baseConfig: default
      deviceServiceCircuitBreaker:
        baseConfig: default
      ingestionServiceCircuitBreaker:
        baseConfig: default
      usageServiceCircuitBreaker:
        baseConfig: default
      insightServiceCircuitBreaker:
        baseConfig: default
  timelimiter:
    instances:
      insightServiceCircuitBreaker:
        timeoutDuration: 120s

keycloak:
  auth:
    jwk-set-uri: http://localhost:8091/realms/het-security-realm/protocol/openid-connect/certs


security:
  excluded:
    urls: /actuator/**,/swagger-ui.html,/swagger-ui/**,/v3/api-docs/**,/aggregate/**

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: User Service
        url: /aggregate/user-service/v3/api-docs
      - name: Device Service
        url: /aggregate/device-service/v3/api-docs
      - name: Ingestion Service
        url: /aggregate/ingestion-service/v3/api-docs
      - name: Usage Service
        url: /aggregate/usage-service/v3/api-docs
      - name: Insight Service
        url: /aggregate/insight-service/v3/api-docs
